version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10.12.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: npx lerna bootstrap
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
            - ./packages/components/node_modules
            - ./packages/extension/node_modules
            - ./packages/moderator/node_modules
            - ./packages/services/node_modules
      - run:
          name: Build
          command: npx lerna run build
      - run:
          name: Test
          command: npx lerna run test:ci
      - store_test_results:
          path: ./test-results
      - store_artifacts:
          path: ./test-results
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
            - packages
  deploy_mod:
    docker:
      - image: circleci/node:10.12.0
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Deploy to netlify
          command: yarn netlify deploy --dir dist --prod --message $CIRCLE_SHA1
          working_directory: packages/moderator
  deploy_storybook:
    docker:
      - image: circleci/node:10.12.0
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Build storybook
          command: yarn build-storybook
          working_directory: packages/components
      - run:
          name: Deploy to netlify
          command: yarn netlify deploy --dir storybook-static --prod --message $CIRCLE_SHA1
          working_directory: packages/components

workflows:
  build:
    jobs:
      - build
      - deploy_mod:
          requires:
            - build
          context: MOD
          filters:
            branches:
              only:
                - master
      - deploy_storybook:
          requires:
            - build
          context: MOD
          filters:
            branches:
              only:
                - master