version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10.23.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npx lerna bootstrap
      - run:
          name: Build
          command: npx lerna run build
      - run:
          name: Test
          command: npx lerna run test:ci
      - run:
          name: Zip
          command: yarn run build:all
          working_directory: packages/extension
      - store_test_results:
          path: ./test-results
      - store_artifacts:
          path: ./packages/extension/dist-zip
      - persist_to_workspace:
          root: .
          paths:
            - packages
  deploy_mod:
    docker:
      - image: circleci/node:10.23.0
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Deploy to netlify
          command: yarn netlify deploy --dir dist --prod --message $CIRCLE_SHA1
          working_directory: packages/moderator
  deploy_storybook:
    docker:
      - image: circleci/node:10.23.0
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Build storybook
          command: yarn build-storybook
          working_directory: packages/components
      - run:
          name: Deploy to netlify
          command: yarn netlify deploy --dir storybook-static --prod --message $CIRCLE_SHA1
          working_directory: packages/components

workflows:
  build:
    jobs:
      - build
      - deploy_mod:
          requires:
            - build
          context: MOD
          filters:
            branches:
              only:
                - master
      - deploy_storybook:
          requires:
            - build
          context: STORYBOOK
          filters:
            branches:
              only:
                - master